name: .NET Build & Release

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-release:
    runs-on: windows-latest

    env:
      Project_Path: CS2Cheat.csproj
      Output_Dir: publish

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Get last commit message
      id: last_commit
      shell: pwsh
      run: |
        $msg = git log -1 --pretty=%B
        "commit_message=$msg" >> $env:GITHUB_OUTPUT

    - name: Calculate next tag version
      id: tag
      shell: pwsh
      run: |
